[package]
name = "create_measurements"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = { version = "6.0.1", features = ["inline", "rayon"] }
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.10.0"
