name: Benchmarkery
on: push

jobs:
  bench:
    needs: generate-measurement
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install minimal nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly

      - name: Cache measurements.txt
        id: measurements
        uses: actions/cache@v3
        env:
          cache-name: measurements
        with:
          path: ./measurements.txt
          key: measurements
          enableCrossOsArchive: true

      - name: Build
        run: cargo +nightly build -r

      - name: Benchmark
        run: cargo +nightly run -r
  generate-measurement:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache measurements.txt
        id: measurements
        uses: actions/cache@v3
        env:
          cache-name: measurements
        with:
          path: ./measurements.txt
          key: measurements
          enableCrossOsArchive: true
      - if: ${{ steps.measurements.outputs.cache-hit != 'true' }}
        name: Generate measurements.txt
        working-directory: scripts/create_measurements
        run: cargo +nightly run -r -- 1_000_000_000
